clear-transparent:
  card-mod-theme: clear-transparent
  card-mod-root: |
    :host {
      --menu-border-width: 4px;
      --menu-background-color: rgb(24, 24, 24);

      --menu-active-button-color: white;
      --menu-active-button-background-color: rgba(208, 208, 208, 0.5);

      --menu-inactive-button-color: white;
      --menu-inactive-button-background-color: transparent;

      --icon-active-color: rgba(255, 255, 255, 0.05);
      --icon-active-background-color: rgb(140, 245, 255);

      --icon-inactive-color: var(--icon-active-color);
      --icon-inactive-background-color: rgba(255, 255, 255, 0.05);

      --card-background-color: var(--menu-background-color);
      --card-border-radius: 20px;

      --sensor-icon-color: white;
      --sensor-border-color: var(--icon-inactive-background-color);
      --sensor-border-width: 3px;

      --default-button-icon-color: white;
      --default-button-background-color: rgba(255, 255, 255, 0.05);
      --first-button-icon-color: white;
      --first-button-background-color: rgb(90, 172, 181);
      --second-button-icon-color: white;
      --second-button-background-color: rgb(250, 172, 104);
      --third-button-icon-color: white;
      --third-button-background-color: rgb(174, 104, 250);
    }
  card-mod-view-yaml: |
    hui-sections-view $: |
      .container {
        padding: 14px 0 !important;
      }
            

  # Supprime les arrondis (0px partout)
  ha-card-border-radius: "0px"
  ha-card-border-width: "0px"

  # Rend les fonds de cartes transparents
  ha-card-background: "black"

  # Supprime les ombres et bordures
  ha-card-box-shadow: "none"
  ha-card-border-color: "rgba(0,0,0,0)"

  # Optionnel : supprime les bordures des boutons
  modes:
    light:
      card-background-color: "black"
    dark:
      card-background-color: "black"

  hide-dialog-border: "none"
  paper-item-icon-color: "var(--primary-text-color)"